//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDBEntities : DbContext
    {
        public HospitalDBEntities()
            : base("name=HospitalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DrugAllotment> DrugAllotments { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<VPatientsTreatment> VPatientsTreatments { get; set; }
        public virtual DbSet<VStaffDepartment> VStaffDepartments { get; set; }
    }
}
