//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgesEarnedByUser
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BadgeID { get; set; }
        public Nullable<System.DateTime> DateOfEarned { get; set; }
    
        public virtual Badge Badge { get; set; }
        public virtual User User { get; set; }
    }
}
