//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Badge()
        {
            this.BadgesEarnedByUsers = new HashSet<BadgesEarnedByUser>();
        }
    
        public int BadgeID { get; set; }
        public string BadgeName { get; set; }
        public string BadgeCategory { get; set; }
        public string BadgeDescription { get; set; }
        public string BadgeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadgesEarnedByUser> BadgesEarnedByUsers { get; set; }
    }
}
