//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobProfile
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string JobType { get; set; }
        public string Role { get; set; }
        public string JobSearchStatus { get; set; }
        public string Industry { get; set; }
        public Nullable<decimal> MinAnnualSalary { get; set; }
        public Nullable<int> MinExperience { get; set; }
        public Nullable<int> MaxExperience { get; set; }
    
        public virtual User User { get; set; }
    }
}
