//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Answers = new HashSet<Answer>();
            this.BadgesEarnedByUsers = new HashSet<BadgesEarnedByUser>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.CompaniesToExcludes = new HashSet<CompaniesToExclude>();
            this.Educations = new HashSet<Education>();
            this.IndustriesToExcludes = new HashSet<IndustriesToExclude>();
            this.JobProfiles = new HashSet<JobProfile>();
            this.Questions = new HashSet<Question>();
            this.TechnologiesUsedAsStudents = new HashSet<TechnologiesUsedAsStudent>();
            this.TechnologiesUsedByUserInJobs = new HashSet<TechnologiesUsedByUserInJob>();
            this.TechPreferNotToWorkWiths = new HashSet<TechPreferNotToWorkWith>();
            this.TechWantToWorkWiths = new HashSet<TechWantToWorkWith>();
            this.WhereUserLikeToWorks = new HashSet<WhereUserLikeToWork>();
            this.WorkExperiences = new HashSet<WorkExperience>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public Nullable<int> VisitedDays { get; set; }
        public string GitHub { get; set; }
        public string Twitter { get; set; }
        public Nullable<int> Reputaion { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public Nullable<int> ProfileViews { get; set; }
        public string AboutUser { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadgesEarnedByUser> BadgesEarnedByUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompaniesToExclude> CompaniesToExcludes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustriesToExclude> IndustriesToExcludes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobProfile> JobProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologiesUsedAsStudent> TechnologiesUsedAsStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologiesUsedByUserInJob> TechnologiesUsedByUserInJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechPreferNotToWorkWith> TechPreferNotToWorkWiths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechWantToWorkWith> TechWantToWorkWiths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhereUserLikeToWork> WhereUserLikeToWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
    }
}
